package emitter

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"strings"

	"github.com/walnuts1018/go-adtgen/internal/model"
)

func Render(pkgName string, generated []model.GeneratedType) (string, error) {
	return RenderForPackage("", pkgName, generated)
}

func RenderForPackage(pkgPath string, pkgName string, generated []model.GeneratedType) (string, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by go-adtgen. DO NOT EDIT.\n")
	buf.WriteString("//go:build !adtgen_generate\n\n")
	buf.WriteString("package " + pkgName + "\n\n")

	imports := collectImports(pkgPath, generated)
	if len(imports) > 0 {
		buf.WriteString("import (\n")
		for _, path := range imports {
			buf.WriteString(fmt.Sprintf("\t%q\n", path))
		}
		buf.WriteString(")\n\n")
	}

	qualifier := func(typePkg *types.Package) string {
		if typePkg == nil {
			return ""
		}
		if pkgPath != "" && typePkg.Path() == pkgPath {
			return ""
		}
		return typePkg.Name()
	}

	for i, generatedType := range generated {
		if i > 0 {
			buf.WriteString("\n")
		}

		if generatedType.Kind == model.DeclarationKindSum && generatedType.Sum != nil {
			renderSumType(&buf, generatedType, qualifier)
			continue
		}

		renderProductType(&buf, generatedType, qualifier)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", err
	}

	return string(formatted), nil
}

func collectImports(pkgName string, generated []model.GeneratedType) []string {
	seen := make(map[string]struct{})

	for _, generatedType := range generated {
		if generatedType.Kind == model.DeclarationKindSum && generatedType.Sum != nil {
			seen["bytes"] = struct{}{}
			seen["encoding/json"] = struct{}{}
			seen["fmt"] = struct{}{}
			seen["io"] = struct{}{}
			for _, variant := range generatedType.Sum.Variants {
				collectTypeImports(pkgName, variant.Type, seen)
			}
			for _, field := range generatedType.Sum.CommonFields {
				collectTypeImports(pkgName, field.Type, seen)
			}
			continue
		}
		for _, input := range generatedType.Inputs {
			collectTypeImports(pkgName, input.Type, seen)
		}
		for _, field := range generatedType.Fields {
			collectTypeImports(pkgName, field.Type, seen)
		}
	}

	imports := make([]string, 0, len(seen))
	for path := range seen {
		imports = append(imports, path)
	}
	sort.Strings(imports)
	return imports
}

func collectTypeImports(pkgPath string, typ types.Type, seen map[string]struct{}) {
	if typ == nil {
		return
	}

	switch t := typ.(type) {
	case *types.Basic:
		return
	case *types.Pointer:
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Slice:
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Array:
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Map:
		collectTypeImports(pkgPath, t.Key(), seen)
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Chan:
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Signature:
		if recv := t.Recv(); recv != nil {
			collectTypeImports(pkgPath, recv.Type(), seen)
		}
		collectTupleImports(pkgPath, t.Params(), seen)
		collectTupleImports(pkgPath, t.Results(), seen)
	case *types.Struct:
		for i := 0; i < t.NumFields(); i++ {
			collectTypeImports(pkgPath, t.Field(i).Type(), seen)
		}
	case *types.Interface:
		for i := 0; i < t.NumEmbeddeds(); i++ {
			collectTypeImports(pkgPath, t.EmbeddedType(i), seen)
		}
	case *types.Named:
		if obj := t.Obj(); obj != nil && obj.Pkg() != nil && obj.Pkg().Path() != pkgPath {
			seen[obj.Pkg().Path()] = struct{}{}
		}
		if args := t.TypeArgs(); args != nil {
			for i := 0; i < args.Len(); i++ {
				collectTypeImports(pkgPath, args.At(i), seen)
			}
		}
	case *types.Alias:
		if obj := t.Obj(); obj != nil && obj.Pkg() != nil && obj.Pkg().Path() != pkgPath {
			seen[obj.Pkg().Path()] = struct{}{}
		}
		collectTypeImports(pkgPath, types.Unalias(t), seen)
	case *types.TypeParam:
		return
	case *types.Union:
		for i := 0; i < t.Len(); i++ {
			collectTypeImports(pkgPath, t.Term(i).Type(), seen)
		}
	case *types.Tuple:
		collectTupleImports(pkgPath, t, seen)
	}
}

func collectTupleImports(pkgPath string, tuple *types.Tuple, seen map[string]struct{}) {
	if tuple == nil {
		return
	}
	for i := 0; i < tuple.Len(); i++ {
		collectTypeImports(pkgPath, tuple.At(i).Type(), seen)
	}
}

func renderProductType(buf *bytes.Buffer, generatedType model.GeneratedType, qualifier types.Qualifier) {
	buf.WriteString("type ")
	buf.WriteString(generatedType.Name)
	if len(generatedType.TypeParameters) > 0 {
		buf.WriteString("[")
		buf.WriteString(strings.Join(generatedType.TypeParameters, ", "))
		buf.WriteString("]")
	}
	buf.WriteString(" struct {\n")

	for _, field := range generatedType.Fields {
		buf.WriteString("\t")
		if !field.Anonymous {
			buf.WriteString(field.Name)
			buf.WriteString(" ")
		}
		buf.WriteString(types.TypeString(field.Type, qualifier))
		if field.Tag != "" {
			buf.WriteString(fmt.Sprintf(" `%s`", field.Tag))
		}
		buf.WriteString("\n")
	}

	buf.WriteString("}\n")

	if len(generatedType.Inputs) == 0 {
		return
	}

	buf.WriteString("\n\n")
	renderConstructor(buf, generatedType, qualifier)

	for _, input := range generatedType.Inputs {
		buf.WriteString("\n\n")
		renderSplitMethod(buf, generatedType, input, qualifier)
	}
}

func renderSumType(buf *bytes.Buffer, generatedType model.GeneratedType, qualifier types.Qualifier) {
	buf.WriteString("type ")
	buf.WriteString(generatedType.Name)
	buf.WriteString(" interface {\n")
	buf.WriteString("\tis")
	buf.WriteString(generatedType.Name)
	buf.WriteString("()\n")
	for _, variant := range generatedType.Sum.Variants {
		buf.WriteString("\tAs")
		buf.WriteString(variant.TypeName)
		buf.WriteString("() (")
		buf.WriteString(types.TypeString(variant.Type, qualifier))
		buf.WriteString(", bool)\n")
	}
	for _, field := range generatedType.Sum.CommonFields {
		buf.WriteString("\t")
		buf.WriteString(field.GetterName)
		buf.WriteString("() ")
		buf.WriteString(types.TypeString(field.Type, qualifier))
		buf.WriteString("\n")
		buf.WriteString("\t")
		buf.WriteString(field.SetterName)
		buf.WriteString("(")
		buf.WriteString(types.TypeString(field.Type, qualifier))
		buf.WriteString(")\n")
	}
	buf.WriteString("}\n\n")

	for _, variant := range generatedType.Sum.Variants {
		renderSumVariantMethods(buf, generatedType, variant, qualifier)
		buf.WriteString("\n")
	}

	renderSumMatchFunctions(buf, generatedType, qualifier)
	buf.WriteString("\n")
	renderSumUnmarshalFunction(buf, generatedType, qualifier)
}

func renderSumVariantMethods(buf *bytes.Buffer, generatedType model.GeneratedType, variant model.GeneratedSumVariant, qualifier types.Qualifier) {
	receiverType := "*" + types.TypeString(variant.Type, qualifier)
	valueType := types.TypeString(variant.Type, qualifier)

	buf.WriteString("func (")
	buf.WriteString(receiverType)
	buf.WriteString(") is")
	buf.WriteString(generatedType.Name)
	buf.WriteString("() {}\n\n")

	for _, target := range generatedType.Sum.Variants {
		buf.WriteString("func (x ")
		buf.WriteString(receiverType)
		buf.WriteString(") As")
		buf.WriteString(target.TypeName)
		buf.WriteString("() (")
		buf.WriteString(types.TypeString(target.Type, qualifier))
		buf.WriteString(", bool) {\n")
		buf.WriteString("\tif x == nil {\n")
		buf.WriteString("\t\tvar zero ")
		buf.WriteString(types.TypeString(target.Type, qualifier))
		buf.WriteString("\n\t\treturn zero, false\n\t}\n")
		if target.TypeName == variant.TypeName {
			buf.WriteString("\treturn *x, true\n")
		} else {
			buf.WriteString("\tvar zero ")
			buf.WriteString(types.TypeString(target.Type, qualifier))
			buf.WriteString("\n\t\treturn zero, false\n")
		}
		buf.WriteString("}\n\n")
	}

	index := variantIndex(generatedType.Sum.Variants, variant.TypeName)
	for _, field := range generatedType.Sum.CommonFields {
		path := selectorPath("x", field.Paths[index])

		buf.WriteString("func (x ")
		buf.WriteString(receiverType)
		buf.WriteString(") ")
		buf.WriteString(field.GetterName)
		buf.WriteString("() ")
		buf.WriteString(types.TypeString(field.Type, qualifier))
		buf.WriteString(" {\n\treturn ")
		buf.WriteString(path)
		buf.WriteString("\n}\n\n")

		buf.WriteString("func (x ")
		buf.WriteString(receiverType)
		buf.WriteString(") ")
		buf.WriteString(field.SetterName)
		buf.WriteString("(v ")
		buf.WriteString(types.TypeString(field.Type, qualifier))
		buf.WriteString(") {\n\t")
		buf.WriteString(path)
		buf.WriteString(" = v\n}\n\n")
	}

	_ = valueType
}

func renderSumMatchFunctions(buf *bytes.Buffer, generatedType model.GeneratedType, qualifier types.Qualifier) {
	buf.WriteString("func Match")
	buf.WriteString(generatedType.Name)
	buf.WriteString("[T any](v ")
	buf.WriteString(generatedType.Name)
	buf.WriteString(", ")
	for i, variant := range generatedType.Sum.Variants {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString("when")
		buf.WriteString(variant.TypeName)
		buf.WriteString(" func(")
		buf.WriteString(types.TypeString(variant.Type, qualifier))
		buf.WriteString(") T")
	}
	buf.WriteString(") T {\n\tswitch x := v.(type) {\n")
	for _, variant := range generatedType.Sum.Variants {
		buf.WriteString("\tcase *")
		buf.WriteString(types.TypeString(variant.Type, qualifier))
		buf.WriteString(":\n\t\treturn when")
		buf.WriteString(variant.TypeName)
		buf.WriteString("(*x)\n")
	}
	buf.WriteString("\tdefault:\n\t\tpanic(\"unreachable generated match for ")
	buf.WriteString(generatedType.Name)
	buf.WriteString("\")\n\t}\n}\n\n")

	buf.WriteString("func Match")
	buf.WriteString(generatedType.Name)
	buf.WriteString("2[S, T any](v ")
	buf.WriteString(generatedType.Name)
	buf.WriteString(", ")
	for i, variant := range generatedType.Sum.Variants {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString("when")
		buf.WriteString(variant.TypeName)
		buf.WriteString(" func(")
		buf.WriteString(types.TypeString(variant.Type, qualifier))
		buf.WriteString(") (S, T)")
	}
	buf.WriteString(") (S, T) {\n\tswitch x := v.(type) {\n")
	for _, variant := range generatedType.Sum.Variants {
		buf.WriteString("\tcase *")
		buf.WriteString(types.TypeString(variant.Type, qualifier))
		buf.WriteString(":\n\t\treturn when")
		buf.WriteString(variant.TypeName)
		buf.WriteString("(*x)\n")
	}
	buf.WriteString("\tdefault:\n\t\tpanic(\"unreachable generated match for ")
	buf.WriteString(generatedType.Name)
	buf.WriteString("\")\n\t}\n}\n")
}

func renderSumUnmarshalFunction(buf *bytes.Buffer, generatedType model.GeneratedType, qualifier types.Qualifier) {
	buf.WriteString("func Unmarshal")
	buf.WriteString(generatedType.Name)
	buf.WriteString("(data []byte) (")
	buf.WriteString(generatedType.Name)
	buf.WriteString(", error) {\n\tvar result ")
	buf.WriteString(generatedType.Name)
	buf.WriteString("\n\tmatches := 0\n")

	for _, variant := range generatedType.Sum.Variants {
		typeString := types.TypeString(variant.Type, qualifier)
		buf.WriteString("\t{\n\t\tvar candidate ")
		buf.WriteString(typeString)
		buf.WriteString("\n\t\tdecoder := json.NewDecoder(bytes.NewReader(data))\n\t\tdecoder.DisallowUnknownFields()\n")
		buf.WriteString("\t\tif err := decoder.Decode(&candidate); err == nil {\n")
		buf.WriteString("\t\t\tvar trailing struct{}\n")
		buf.WriteString("\t\t\tif err := decoder.Decode(&trailing); err == io.EOF {\n")
		buf.WriteString("\t\t\t\tmatches++\n\t\t\t\tresult = &candidate\n\t\t\t}\n\t\t}\n\t}\n")
	}

	buf.WriteString("\tif matches == 1 {\n\t\treturn result, nil\n\t}\n")
	buf.WriteString("\tif matches == 0 {\n\t\treturn nil, fmt.Errorf(\"no variants of ")
	buf.WriteString(generatedType.Name)
	buf.WriteString(" matched JSON\")\n\t}\n")
	buf.WriteString("\treturn nil, fmt.Errorf(\"multiple variants of ")
	buf.WriteString(generatedType.Name)
	buf.WriteString(" matched JSON\")\n}\n")
}

func selectorPath(root string, path []string) string {
	if len(path) == 0 {
		return root
	}
	return root + "." + strings.Join(path, ".")
}

func renderConstructor(buf *bytes.Buffer, generatedType model.GeneratedType, qualifier types.Qualifier) {
	buf.WriteString("func New")
	buf.WriteString(renderGeneratedTypeName(generatedType, true))
	buf.WriteString("(")
	for i, input := range generatedType.Inputs {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(input.ParameterName)
		buf.WriteString(" ")
		buf.WriteString(types.TypeString(input.Type, qualifier))
	}
	buf.WriteString(") ")
	buf.WriteString(renderGeneratedTypeName(generatedType, false))
	buf.WriteString(" {\n\treturn ")
	buf.WriteString(renderGeneratedTypeName(generatedType, false))
	buf.WriteString("{\n")

	seen := make(map[string]struct{})
	for _, input := range generatedType.Inputs {
		for _, fieldName := range input.FieldNames {
			if _, ok := seen[fieldName]; ok {
				// Duplicate fields have already been verified by ComposeFields to be
				// structurally identical anonymous fields. Thus, initializing from
				// the first encountered input is safe and correct.
				continue
			}
			seen[fieldName] = struct{}{}
			buf.WriteString("\t\t")
			buf.WriteString(fieldName)
			buf.WriteString(": ")
			buf.WriteString(input.ParameterName)
			buf.WriteString(".")
			buf.WriteString(fieldName)
			buf.WriteString(",\n")
		}
	}

	buf.WriteString("\t}\n}\n")
}

func renderSplitMethod(buf *bytes.Buffer, generatedType model.GeneratedType, input model.GeneratedInput, qualifier types.Qualifier) {
	buf.WriteString("func (x ")
	buf.WriteString(renderGeneratedTypeName(generatedType, false))
	buf.WriteString(") ")
	buf.WriteString(input.MethodName)
	buf.WriteString("() ")
	buf.WriteString(types.TypeString(input.Type, qualifier))
	buf.WriteString(" {\n\treturn ")
	buf.WriteString(types.TypeString(input.Type, qualifier))
	buf.WriteString("{\n")
	for _, fieldName := range input.FieldNames {
		buf.WriteString("\t\t")
		buf.WriteString(fieldName)
		buf.WriteString(": x.")
		buf.WriteString(fieldName)
		buf.WriteString(",\n")
	}
	buf.WriteString("\t}\n}\n")
}

func renderGeneratedTypeName(generatedType model.GeneratedType, withConstraints bool) string {
	if len(generatedType.TypeParameters) == 0 {
		return generatedType.Name
	}

	params := generatedType.TypeParameters
	if !withConstraints {
		params = renderTypeParameterNames(generatedType.TypeParameters)
	}

	return generatedType.Name + "[" + strings.Join(params, ", ") + "]"
}

func renderTypeParameterNames(typeParameters []string) []string {
	names := make([]string, 0, len(typeParameters))
	for _, parameter := range typeParameters {
		fields := strings.Fields(parameter)
		if len(fields) == 0 {
			continue
		}
		names = append(names, strings.TrimSuffix(fields[0], ","))
	}
	return names
}

func variantIndex(variants []model.GeneratedSumVariant, typeName string) int {
	for i, variant := range variants {
		if variant.TypeName == typeName {
			return i
		}
	}
	return -1
}
