package emitter

import (
	"go/token"
	"go/types"
	"strings"
	"testing"

	"github.com/walnuts1018/go-adtgen/internal/model"
)

func TestRenderIncludesHeaderPackageAndTypeDefinition(t *testing.T) {
	src, err := Render("sample", []model.GeneratedType{
		{
			Name: "AB",
			Fields: []model.GeneratedField{
				{Name: "ID", Type: types.Typ[types.String]},
			},
		},
	})
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	for _, want := range []string{
		"// Code generated by go-adtgen. DO NOT EDIT.",
		"//go:build !adtgen_generate",
		"package sample",
		"type AB struct",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("Render() output missing %q:\n%s", want, src)
		}
	}
}

func TestRenderIncludesImportsTypeParametersAnonymousFieldsAndTags(t *testing.T) {
	timePkg := types.NewPackage("time", "time")
	timeType := types.NewNamed(
		types.NewTypeName(token.NoPos, timePkg, "Time", nil),
		types.NewStruct(nil, nil),
		nil,
	)
	depPkg := types.NewPackage("example.com/dep", "dep")
	embeddedType := types.NewNamed(
		types.NewTypeName(token.NoPos, depPkg, "Embedded", nil),
		types.NewStruct(nil, nil),
		nil,
	)
	typeParam := types.NewTypeParam(types.NewTypeName(token.NoPos, nil, "T", nil), types.Universe.Lookup("any").Type())

	src, err := Render("sample", []model.GeneratedType{
		{
			Name:           "Pair",
			TypeParameters: []string{"T comparable", "U interface{ String() string }"},
			Fields: []model.GeneratedField{
				{Name: "CreatedAt", Type: timeType, Tag: `json:"created_at"`},
				{Name: "Embedded", Type: types.NewPointer(embeddedType), Anonymous: true},
				{Name: "Value", Type: typeParam},
			},
		},
	})
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	for _, want := range []string{
		"import (\n\t\"example.com/dep\"\n\t\"time\"\n)",
		"type Pair[T comparable, U interface{ String() string }] struct {",
		"CreatedAt time.Time `json:\"created_at\"`",
		"*dep.Embedded",
		"Value T",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("Render() output missing %q:\n%s", want, src)
		}
	}

	createdAtIndex := strings.Index(src, "CreatedAt time.Time")
	embeddedIndex := strings.Index(src, "*dep.Embedded")
	valueIndex := strings.Index(src, "Value T")
	if createdAtIndex < 0 || createdAtIndex >= embeddedIndex || embeddedIndex >= valueIndex {
		t.Fatalf("Render() did not preserve field order:\n%s", src)
	}
}

func TestRenderIncludesConstructorAndSplitMethods(t *testing.T) {
	aType := types.NewNamed(
		types.NewTypeName(token.NoPos, nil, "A", nil),
		types.NewStruct([]*types.Var{
			types.NewField(token.NoPos, nil, "ID", types.Typ[types.String], false),
		}, nil),
		nil,
	)
	bType := types.NewNamed(
		types.NewTypeName(token.NoPos, nil, "B", nil),
		types.NewStruct([]*types.Var{
			types.NewField(token.NoPos, nil, "Name", types.Typ[types.String], false),
		}, nil),
		nil,
	)

	src, err := Render("sample", []model.GeneratedType{
		{
			Name:           "AB",
			TypeParameters: []string{"T any"},
			Fields: []model.GeneratedField{
				{Name: "ID", Type: types.Typ[types.String]},
				{Name: "Name", Type: types.Typ[types.String]},
			},
			Inputs: []model.GeneratedInput{
				{
					Expression:    "A[T]",
					ParameterName: "a",
					Type:          aType,
					MethodName:    "ToA",
					FieldNames:    []string{"ID"},
				},
				{
					Expression:    "B",
					ParameterName: "b",
					Type:          bType,
					MethodName:    "ToB",
					FieldNames:    []string{"Name"},
				},
			},
		},
	})
	if err != nil {
		t.Fatal(err)
	}

	for _, want := range []string{
		"func NewAB[T any](a A, b B) AB[T] {",
		"func (x AB[T]) ToA() A {",
		"func (x AB[T]) ToB() B {",
		"return AB[T]{",
		"ID:   a.ID,",
		"Name: b.Name,",
		"return A{",
		"return B{",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("missing %q in output:\n%s", want, src)
		}
	}
}

func TestRenderForPackageImportsExternalTypeWithSamePackageName(t *testing.T) {
	samplePkg := types.NewPackage("example.com/other/sample", "sample")
	externalType := types.NewNamed(
		types.NewTypeName(token.NoPos, samplePkg, "External", nil),
		types.NewStruct(nil, nil),
		nil,
	)

	src, err := RenderForPackage("example.com/current/sample", "sample", []model.GeneratedType{
		{
			Name: "AB",
			Fields: []model.GeneratedField{
				{Name: "Value", Type: externalType},
			},
		},
	})
	if err != nil {
		t.Fatalf("RenderForPackage() error = %v", err)
	}

	for _, want := range []string{
		"\"example.com/other/sample\"",
		"Value sample.External",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("RenderForPackage() output missing %q:\n%s", want, src)
		}
	}
}

func TestRenderIncludesSumInterfaceMethodsAndHelpers(t *testing.T) {
	pkg := types.NewPackage("example.com/sample", "sample")
	hogeType := types.NewNamed(
		types.NewTypeName(token.NoPos, pkg, "Hoge", nil),
		types.NewStruct([]*types.Var{
			types.NewField(token.NoPos, pkg, "ID", types.Typ[types.String], false),
		}, nil),
		nil,
	)
	fugaType := types.NewNamed(
		types.NewTypeName(token.NoPos, pkg, "Fuga", nil),
		types.NewStruct([]*types.Var{
			types.NewField(token.NoPos, pkg, "ID", types.Typ[types.String], false),
		}, nil),
		nil,
	)

	src, err := RenderForPackage("example.com/sample", "sample", []model.GeneratedType{
		{
			Kind: model.DeclarationKindSum,
			Name: "HogeOrFuga",
			Sum: &model.GeneratedSum{
				GenerateSetters: true,
				InterfaceMethods: []model.GeneratedInterfaceMethod{
					{
						Name:      "String",
						Signature: types.NewSignatureType(nil, nil, nil, nil, types.NewTuple(types.NewVar(token.NoPos, nil, "", types.Typ[types.String])), false),
					},
				},
				Variants: []model.GeneratedSumVariant{
					{Expression: "Hoge", Type: hogeType, TypeName: "Hoge"},
					{Expression: "Fuga", Type: fugaType, TypeName: "Fuga"},
				},
				CommonFields: []model.GeneratedCommonField{
					{
						Name:       "ID",
						Type:       types.Typ[types.String],
						GetterName: "GetID",
						SetterName: "SetID",
						Paths: [][]string{
							{"ID"},
							{"ID"},
						},
					},
				},
			},
		},
	})
	if err != nil {
		t.Fatalf("RenderForPackage() error = %v", err)
	}

	for _, want := range []string{
		"import (\n\t\"bytes\"\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"io\"\n)",
		"type HogeOrFuga interface {",
		"isHogeOrFuga()",
		"String() string",
		"AsHoge() (Hoge, bool)",
		"AsFuga() (Fuga, bool)",
		"GetID() string",
		"SetID(string)",
		"func (*Hoge) isHogeOrFuga() {}",
		"func (x *Hoge) AsHoge() (Hoge, bool) {",
		"func (x *Hoge) AsFuga() (Fuga, bool) {",
		"func (x *Hoge) GetID() string {",
		"func (x *Hoge) SetID(v string) {",
		"func MatchHogeOrFuga[R any](v HogeOrFuga, whenHoge func(Hoge) R, whenFuga func(Fuga) R) R {",
		"func MatchHogeOrFuga2[R1, R2 any](v HogeOrFuga, whenHoge func(Hoge) (R1, R2), whenFuga func(Fuga) (R1, R2)) (R1, R2) {",
		"func UnmarshalHogeOrFuga(data []byte) (HogeOrFuga, error) {",
		"decoder := json.NewDecoder(bytes.NewReader(data))",
		"result = &candidate",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("RenderForPackage() output missing %q:\n%s", want, src)
		}
	}
}

func TestRenderOmitsSumSettersWhenDisabled(t *testing.T) {
	pkg := types.NewPackage("example.com/sample", "sample")
	hogeType := types.NewNamed(
		types.NewTypeName(token.NoPos, pkg, "Hoge", nil),
		types.NewStruct([]*types.Var{
			types.NewField(token.NoPos, pkg, "ID", types.Typ[types.String], false),
		}, nil),
		nil,
	)
	fugaType := types.NewNamed(
		types.NewTypeName(token.NoPos, pkg, "Fuga", nil),
		types.NewStruct([]*types.Var{
			types.NewField(token.NoPos, pkg, "ID", types.Typ[types.String], false),
		}, nil),
		nil,
	)

	src, err := RenderForPackage("example.com/sample", "sample", []model.GeneratedType{
		{
			Kind: model.DeclarationKindSum,
			Name: "HogeOrFuga",
			Sum: &model.GeneratedSum{
				GenerateSetters: false,
				Variants: []model.GeneratedSumVariant{
					{Expression: "Hoge", Type: hogeType, TypeName: "Hoge"},
					{Expression: "Fuga", Type: fugaType, TypeName: "Fuga"},
				},
				CommonFields: []model.GeneratedCommonField{
					{
						Name:       "ID",
						Type:       types.Typ[types.String],
						GetterName: "GetID",
						SetterName: "SetID",
						Paths: [][]string{
							{"ID"},
							{"ID"},
						},
					},
				},
			},
		},
	})
	if err != nil {
		t.Fatalf("RenderForPackage() error = %v", err)
	}
	if strings.Contains(src, "SetID(string)") {
		t.Fatalf("RenderForPackage() unexpectedly emitted setter in interface:\n%s", src)
	}
	if strings.Contains(src, "func (x *Hoge) SetID(v string)") {
		t.Fatalf("RenderForPackage() unexpectedly emitted setter method:\n%s", src)
	}
	if !strings.Contains(src, "GetID() string") {
		t.Fatalf("RenderForPackage() output missing getter:\n%s", src)
	}
}

func TestRenderIncludesSumTypeParametersInInterfaceAndHelpers(t *testing.T) {
	pkg := types.NewPackage("example.com/sample", "sample")
	sumTypeParam := types.NewTypeParam(types.NewTypeName(token.NoPos, nil, "T", nil), types.Universe.Lookup("any").Type())
	leftTypeParam := types.NewTypeParam(types.NewTypeName(token.NoPos, nil, "T", nil), types.Universe.Lookup("any").Type())
	leftOrigin := types.NewNamed(
		types.NewTypeName(token.NoPos, pkg, "Left", nil),
		types.NewStruct([]*types.Var{
			types.NewField(token.NoPos, pkg, "Value", leftTypeParam, false),
		}, nil),
		nil,
	)
	leftOrigin.SetTypeParams([]*types.TypeParam{leftTypeParam})
	rightTypeParam := types.NewTypeParam(types.NewTypeName(token.NoPos, nil, "T", nil), types.Universe.Lookup("any").Type())
	rightOrigin := types.NewNamed(
		types.NewTypeName(token.NoPos, pkg, "Right", nil),
		types.NewStruct([]*types.Var{
			types.NewField(token.NoPos, pkg, "Value", rightTypeParam, false),
		}, nil),
		nil,
	)
	rightOrigin.SetTypeParams([]*types.TypeParam{rightTypeParam})
	leftType, err := types.Instantiate(nil, leftOrigin, []types.Type{sumTypeParam}, false)
	if err != nil {
		t.Fatalf("types.Instantiate(leftOrigin) error = %v", err)
	}
	rightType, err := types.Instantiate(nil, rightOrigin, []types.Type{sumTypeParam}, false)
	if err != nil {
		t.Fatalf("types.Instantiate(rightOrigin) error = %v", err)
	}

	src, err := RenderForPackage("example.com/sample", "sample", []model.GeneratedType{
		{
			Kind:           model.DeclarationKindSum,
			Name:           "Either",
			TypeParameters: []string{"T any"},
			Sum: &model.GeneratedSum{
				Variants: []model.GeneratedSumVariant{
					{Expression: "Left[T]", Type: leftType, TypeName: "Left"},
					{Expression: "Right[T]", Type: rightType, TypeName: "Right"},
				},
			},
		},
	})
	if err != nil {
		t.Fatalf("RenderForPackage() error = %v", err)
	}

	for _, want := range []string{
		"type Either[T any] interface {",
		"func (*Left[T]) isEither() {}",
		"func MatchEither[T any, R any](v Either[T], whenLeft func(Left[T]) R, whenRight func(Right[T]) R) R {",
		"func MatchEither2[T any, R1, R2 any](v Either[T], whenLeft func(Left[T]) (R1, R2), whenRight func(Right[T]) (R1, R2)) (R1, R2) {",
		"func UnmarshalEither[T any](data []byte) (Either[T], error) {",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("RenderForPackage() output missing %q:\n%s", want, src)
		}
	}
}

func TestRenderFileIncludesPassthroughImportsAndDeclarationsBeforeGeneratedCode(t *testing.T) {
	src, err := RenderFile(model.GeneratedFile{
		PackagePath: "example.com/sample",
		PackageName: "sample",
		Imports: []model.PassthroughImport{
			{Path: "fmt"},
		},
		PassthroughDecls: []string{
			"const prefix = \"inline\"",
			"type Inline struct{ Name string }",
			"func UseInline(x Inline) string { return fmt.Sprint(x.Name) }",
		},
		Generated: []model.GeneratedType{
			{
				Name: "Combined",
				Fields: []model.GeneratedField{
					{Name: "Name", Type: types.Typ[types.String]},
				},
			},
		},
	})
	if err != nil {
		t.Fatalf("RenderFile() error = %v", err)
	}

	for _, want := range []string{
		"import \"fmt\"",
		"const prefix = \"inline\"",
		"type Inline struct{ Name string }",
		"func UseInline(x Inline) string",
		"type Combined struct {",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("RenderFile() output missing %q:\n%s", want, src)
		}
	}

	if strings.Index(src, "const prefix") > strings.Index(src, "type Combined struct") {
		t.Fatalf("passthrough declarations were not emitted before generated code:\n%s", src)
	}
}
